export default interface Keluhan {
  id_keluhan: string,
  tgl_masuk: string,
  tgl_approval_katim: string,
  tgl_penanganan_teknisi: string,
  insiden: string,
  nama_ruangan: string,
  hasil_penanganan: string,
  foto_teknisi: string,
  id_teknisi: string,
  foto_user: string,
  nama_alat: string,
  no_seri: string,
  respon_name: string,
  nama_user: string,
  catatan_teknisi: string,
  status: 'Proses' | 'Approval' | 'Selesai',
  detail: {
    deskripsi_keluhan: string,
    foto_mini_1: string,
    foto_zoom_1: string,
    foto_mini_2: string,
    foto_zoom_2: string,
    foto_mini_3: string,
    foto_zoom_3: string,
    foto_penanganan_mini_1: string,
    foto_penanganan_zoom_1: string,
    foto_penanganan_mini_2: string,
    foto_penanganan_zoom_2: string,
    foto_penanganan_mini_3: string,
    foto_penanganan_zoom_3: string,
  }
}